# Book settings
title: Introduction to Python for Humanists
author: William J.B. Mattingly, Tassos Kolydas (translation)
# logo: 'images/chapman-logo.jpg'
execute:
  execute_notebooks: 'off'
parse:
  myst_extended_syntax: true
exclude_patterns:
  - venv*
  - .git
  - .github
  - .ipynb_checkpoints
  - .cursor
  - _build
  - .DS_Store
  - '**.ipynb_checkpoints'
  - markdown
  - streamlit_application
  - CLAUDE.md
  - TRANSLATION_PLAN.md
  - README.md
  - 02_pandas
  - 03_spacy
  - 04_topic_modeling
  - 05_streamlit
  - 06_sna
  - 08_booknlp
  - 09_conclusion
  - other
# Information about where the book exists on the web
repository:
  url: https://github.com/kolydart/python_for_dh # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
html:
  use_edit_page_button: false
  use_issues_button: false
  use_repository_button: false
  use_multitoc_numbering: false
  copyright: ""  # Empty string removes the copyright notice
sphinx:
  config:
    html_show_copyright: false
launch_buttons:
  colab_url: "https://colab.research.google.com"